### ISSUE TITLE
i used bard via bing 

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/Bard#13]

**Comment by acheong08** [comment]
?

**Comment by tekemperor** [comment]
I do not think this is relevant to the project. Unless there is a question or suggestion, you may just want to close the issue.

**Comment by Mrithul-E** [comment]
_I asked code for using bard to bing ai_. bing gives a code using requests in that code there were already a prompt in the var called `prompt` . Below that code there is the result of that code from the bard. _Then I asked how u get result of that code then it is saying_ **bing has it's own api key I thing it is session token for bard that stored in the browser** it use the api key in the code and give the response. Then i change the prompt and asked the result .Then it gives the ans from bard

**Comment by Mrithul-E** [comment]
**Q:** `python code for using google bard from python`

**ANS:**
_Bard is an early experiment from Google that lets you collaborate with generative AI[1](https://blog.google/technology/ai/try-bard/). [You can use Bard to boost your productivity, accelerate your ideas and fuel your curiosity](https://blog.google/technology/ai/try-bard/)[1](https://blog.google/technology/ai/try-bard/). You can sign up to try Bard from Google’s website[2](https://bard.google.com/).

To use Bard from Python, you need to have a valid __Secure-1PSID cookie from your Google account[3](https://github.com/acheong08/Bard). You can use the Bard.py module from Github[3](https://github.com/acheong08/Bard) to interact with Bard’s API. You can import the module and create a Bard object with your session cookie. Then you can use the ask method to send queries to Bard and get responses. Here is an example of how to use Bard from Python:_

```

# Import the Bard module
import Bard

# Create a Bard object with your session cookie
session = "your_session_cookie_here"
bard = Bard.Bard(session)

# Ask Bard a question
question = "What is quantum physics?"
response = bard.ask(question)

# Print the response
print(response)
```
**Q:** `what is the response`

**ANS:**
_The response is what Bard generates based on your question. It may vary depending on the question and the model. Here is an example of a possible response for the question “What is quantum physics?” from Bard:_

`Quantum physics is the branch of physics that studies the behavior of matter and energy at the smallest scales. Quantum physics deals with phenomena that are often counterintuitive and defy classical logic, such as superposition, entanglement, uncertainty and wave-particle duality. Quantum physics has many applications in fields like chemistry, electronics, cryptography and computing.`

**Comment by Mrithul-E** [comment]
when i am using bard from bing first time it give a code using requests now i changed to bard lib

**Comment by acheong08** [comment]
This can go to discussions
