### ISSUE TITLE
Nothing outputs except some google introduction

### ISSUE THREAD

**Issue by wangjiyang** [acheong08/Bard#16]
(venv) oliver@hecs-275203:~/chatbot/tests$ python3 -m Bard

        Bard - A command-line interface to Google's Bard (https://bard.google.com/)
        Repo: github.com/acheong08/Bard

        Enter `alt+enter` or `esc+enter` to send a message.
        
HI^[
^[
^[
Here are the steps on how to get a refund from the IRS:                                                                                                                                           

 1 Check the status of your refund. You can check the status of your refund online at the IRS website or by calling the IRS Refund Hotline at 1-800-829-1954.                                     
 2 If you haven't received your refund, initiate a refund trace. You can initiate a refund trace online at the IRS website or by calling the IRS Refund Hotline at 1-800-829-1954.                
 3 If you still haven't received your refund after initiating a refund trace, you can file Form 3911, Taxpayer Statement Regarding Refund. You can download Form 3911 from the IRS website or by  
   calling the IRS at 1-800-829-1040.                                                                                                                                                             

Here are some additional tips for getting a refund from the IRS:                                                                                                                                  

 • File your tax return on time. The IRS will start processing your refund after you file your tax return. If you file your tax return late, it could delay your refund.                          
 • Make sure your tax return is accurate. If there are any errors on your tax return, it could delay your refund.                                                                                 
 • Use direct deposit. If you have direct deposit set up, your refund will be deposited directly into your bank account. This is usually the fastest way to get your refund.                      
 • Be patient. It can take several weeks for the IRS to process your refund. If you haven't received your refund after four weeks, you can initiate a refund trace.                               

I hope this helps!                                                                                                                                                                                
(venv) oliver@hecs-275203:~/chatbot/tests$ vim test_bard.py 
(venv) oliver@hecs-275203:~/chatbot/tests$ python3 -m Bard

        Bard - A command-line interface to Google's Bard (https://bard.google.com/)
        Repo: github.com/acheong08/Bard

        Enter `alt+enter` or `esc+enter` to send a message.
        
fdHere are the steps on how to clean a dog's ear:                                                                                                                                                   

 1 Gather your supplies. You will need:                                                                                                                                                           
    • A veterinarian-approved ear cleaner                                                                                                                                                         
    • A cotton ball or gauze pad                                                                                                                                                                  
    • A towel                                                                                                                                                                                     
    • A treat (optional)                                                                                                                                                                          
 2 Get your dog comfortable. Have your dog sit or stand still, and reward them with a treat.                                                                                                      
 3 Lift your dog's ear flap. Gently pull up on your dog's ear flap to expose the ear canal.                                                                                                       
 4 Apply the ear cleaner. Pour a small amount of ear cleaner into the ear canal.                                                                                                                  
 5 Massage the base of the ear. Massage the base of the ear for about 30 seconds. This will help to loosen any debris and wax.                                                                    
 6 Wipe away the debris. Use a cotton ball or gauze pad to wipe away any debris that you see in the ear canal.                                                                                    
 7 Repeat on the other ear. Repeat steps 3-6 on the other ear.                                                                                                                                    
 8 Praise your dog. Give your dog a treat and praise them for being good.                                                                                                                         

Here are some additional tips for cleaning your dog's ears:                                                                                                                                       

 • Do not use a cotton swab to clean your dog's ears. This can push the debris further into the ear canal and damage the eardrum.                                                                 
 • Do not use hydrogen peroxide or alcohol to clean your dog's ears. These products can irritate the skin and cause damage.                                                                       
 • If your dog has a lot of earwax, you may need to clean their ears more often. Talk to your veterinarian about how often you should clean your dog's ears.                                      
 • If your dog has any signs of ear infection, such as redness, swelling, or discharge, take them to the veterinarian immediately.                                                                

By following these steps, you can help to keep your dog's ears clean and healthy.

**Comment by acheong08** [comment]
?

**Comment by jrhoads20** [comment]
@wangjiyang 
1. Those outputs are not google introductions they are bards responses to input, I can only assume your inputs.
2. You aren't showing your input, do you have input you can show?
3. What part of this are you labeling as 'Google introduction'?

**Comment by wangjiyang** [comment]
Please check my inputs above. I am typing Hi and send. However even I dont type anything i terminal, these messages just bumping out and python script exists.

**Comment by cameronj86** [comment]
**Try putting your question immediately in the same line that you use to launch Bard instead:** I believe that Bing auto-populates a random fact when it doesn't feel like it receives an input and so that leads me to believe that your prompt is being typed at the wrong time. Try this: 

**oliver@hecs-275203**:~/chatbot/tests$ python3 -m Bard Hi Bard how are you doing?

AFAIK, the only way I know how to replicate the more convo-esque communication with the 'You'  w/ Bard is to explicitly specify the session when launching bard. 

**oliver@hecs-275203**:~/chatbot/tests$ python3 -m Bard --session <insert session cookie here w/o quotes>

You could save that into .bash_alias and call it 'Bard' or something to streamline the process fwiw

**Comment by acheong08** [comment]
You need to give a session

**Comment by acheong08** [comment]
Can you add debug statements to show what is returned?

**Comment by acheong08** [comment]
@fidodido48 
Tracking:
- #28
