### ISSUE TITLE
I can't install Bard library.

### ISSUE THREAD

**Issue by danghuong18** [acheong08/Bard#18]
As the title says, I can't install this library, I have installed it but its code doesn't appear in python's site-packages.

**Comment by QuartzWarrior** [comment]
provide the commands you are running with their responses and I'll take a look at it

**Comment by danghuong18** [comment]
> provide the commands you are running with their responses and I'll take a look at it

I had run the command "pip install GoogleBard" to install this libary and it's done, but when I use in my python code, I can't, because it says library not found.

**Comment by QuartzWarrior** [comment]
Try running `python -m pip install GoogleBard`

**Comment by danghuong18** [comment]
> Try running `python -m pip install GoogleBard`

Oh, it's done but still have this error:
`Traceback (most recent call last):
  File "D:\Bard.py", line 2, in <module>
    from Bard import Chatbot
  File "D:\Bard.py", line 2, in <module>
    from Bard import Chatbot
ImportError: cannot import name 'Chatbot' from partially initialized module 'Bard' (most likely due to a circular import) (D:\Bard.py)`

**Comment by acheong08** [comment]
Bard.py cannot import Bard.

**Comment by acheong08** [comment]
Rename your file
