### ISSUE TITLE
"Google Bard encountered an error" after send many requests

### ISSUE THREAD

**Issue by buaabarty** [acheong08/Bard#23]
```
Google Bard encountered an error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n57\n[["di",141],["af.httprm",141,"-5945089517819816234",1]]\n25\n[["e",4,null,null,132]]\n'.
```

**Comment by AprilNEA** [comment]
I'm curious about how many times ?

**Comment by buaabarty** [comment]
> I'm curious about how many times ?

send about hundreds of requests continuously 🤣

**Comment by jonrhaider** [comment]
Do you think you're hitting an api call limit or do you need to refresh your __Secure-1PSID cookie or SNlM0e values after so many calls?

**Comment by Razilator** [comment]
I wanted to create a bot, but faced exactly the same problem. Didn't send any messages to him.

**Comment by Razilator** [comment]
Everything works with VPN/PROXY, please upgrade the package to pip, so that you can use the new code from the proxy package.

**Comment by Tienduyvo** [comment]
Bard will stop working if you are sending too many requests. This limit is bound to your Google Account.

I have tried to change the account and IP address. Unfortunately, while the web UI is accepting request again. Using the new __Secure-1PSID cookie still lead to the same error.

**Comment by acheong08** [comment]
Rate limits are server side and out of scope as an issue
