### ISSUE TITLE
Updates to Bard not accessible from canadian account

### ISSUE THREAD

**Issue by sangfrois** [acheong08/Bard#25]
Hi there,

First off, thank you for creating these reverse-engineered repos. I've been using them a lot.

I just want to express this so people can confirm whether or not my intuition is right.

I'm canadian, and I've been using a VPN to interact with the website since it came out. Though, I'm pretty sure now i'm not interacting with the updated version as my account is canadian.

If you navigate to the Network tab in Console mode, you will see an object called StreamGenerate.

It refers to a URL : ``https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate?bl=boq_assistant-bard-web-server_20230510.09_p1&_reqid=557387&rt=c``

This is making me doubt that i'm not interacting with the latest LLM, but still with LLaMDA because of regulations. It may be that Google is filtering out requests from accounts in EU and Canada. Here is the [list](https://support.google.com/bard/answer/13575153?hl=en) of accepted countries. Thus, accounts from the EU and Canada would not be able to interact with either [PaLM2 or Gemini](https://blog.google/technology/ai/google-io-2023-keynote-sundar-pichai/#ai-responsibility)

I'm currently in the US and not using a VPN and it still spits out the same URL and ``authuser`` error under the Network tab whenever i'm sending a message (``https://play.google.com/log?format=json&hasfast=true&authuser=0``).

(and yes, I have access to dark mode and export to Docs and Gmail, so part of the update is on).

Can a user with US gmail account verify that ?

Also, I believe this could affect your code @acheong08  in ``self.session.post`` https://github.com/acheong08/Bard/blob/4c53d4ae54753d00f64fd4a89e4005d0e87588d2/src/Bard.py#L128

**Comment by sangfrois** [comment]
Hi to any google employees seeing this :)

**Comment by acheong08** [comment]
Hi. I'm supposed to update the LLM version in the request every once in a while. Have been and still am busy with exams. 

Regarding the PALM/Gemini, those are not available through Bard yet afaik. Gemini is still in training and PALM 2 is rolling out.

The latest version I can access is `20230510.09_p1` which https://github.com/acheong08/Bard/releases/tag/1.0.2 switches to

**Comment by sangfrois** [comment]
Great. Thanks for confirming. 

Good luck on your exams!!
