### ISSUE TITLE
/usr/bin/python3: No module named Bard

### ISSUE THREAD

**Issue by beshoo** [acheong08/Bard#26]
After Installation successfully ....
```

python3 -m Bard -h
/usr/bin/python3: No module named Bard

```

**Comment by acheong08** [comment]
`python3 -m pip install Bard`

**Comment by acheong08** [comment]
pip might be using a different version or not installing properly?

**Comment by beshoo** [comment]
***@***.*** ip2location]$ python3 -m pip install Bard
Collecting Bard
  Downloading
https://files.pythonhosted.org/packages/8e/b5/017c08006778a5ba3de9a338401ea26422e90047b865def503bc6c89bee0/bard-0.1-py3-none-any.whl
Installing collected packages: Bard
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in
main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line
365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in
install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854,
in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line
1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in
move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83,
in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib64/python3.6'

**Comment by acheong08** [comment]
A few key issues:
1. Python 3.6 is not supported
2. Your Python library directory is in /usr/local which can only be accessed by root

**Comment by beshoo** [comment]
```
[MAX]root:[/root]python3 -m pip install Bard
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting Bard
  Downloading https://files.pythonhosted.org/packages/8e/b5/017c08006778a5ba3de9a338401ea26422e90047b865def503bc6c89bee0/bard-0.1-py3-none-any.whl
Installing collected packages: Bard
Successfully installed Bard-0.1
[MAX]root:[/root]python3 -m Bard -h
/usr/bin/python3: No module named Bard
[MAX]root:[/root]


```

**Comment by acheong08** [comment]
`python3 -m pip install GoogleBard`

**Comment by beshoo** [comment]
Now :
```

[MAX]root:[/root]python3 -m Bard -h

        Bard - A command-line interface to Google's Bard (https://bard.google.com/)
        Repo: github.com/acheong08/Bard

        Enter `alt+enter` or `esc+enter` to send a message.

usage: Bard.py [-h] --session SESSION

optional arguments:
  -h, --help         show this help message and exit
  --session SESSION  __Secure-1PSID cookie.

```

**Comment by acheong08** [comment]
Yup. This is correct. Get your session cookie from https://bard.google.com/
