### ISSUE TITLE
SNlM0e value not found in response

### ISSUE THREAD

**Issue by zicas2000** [acheong08/Bard#29]
I have tried to interpret core python code to C# with the help of Chatgpt as I'm just a newbie in this field , It generated the full code to be applicable for integration with Unity. but I have got the error "SNlM0e value not found in response".
I don't know what is the issue, it might be related to my location ?

**Comment by j22-robertson** [comment]
Also having a similar issue in TypeScript, I have even output the result to a log file and am still unable to find SNlM0e to match with after doing crtl+f to manually search.
const snim0eMatch = resp.data.match(/SNlM0e:(.*?)/);

**Comment by zicas2000** [comment]
Now I can get that SNlM0e value but eventually I got 404 bad request, l'm still trying to debug.

**Comment by alienatorZ** [comment]
In python I am having trouble with line 100:`SNlM0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)`

I think maybe the SNlM0e isn't there anymore?

**Comment by aezendc** [comment]
> Now I can get that  but eventually I got 404 bad request, l'm still trying to debug.

Hello what steps did you do to get the SNlM0e value. I am using c# also
