### ISSUE TITLE
from Bard import Chatbot

### ISSUE THREAD

**Issue by samedovzaur** [acheong08/Bard#30]
it doesn't define Bard while using from Bard import Chatbot

**Comment by acheong08** [comment]
Chatbot is Bard

**Comment by acheong08** [comment]
Look at dev example

**Comment by samedovzaur** [comment]
![Screenshot 2023-05-18 at 14 57 16](https://github.com/acheong08/Bard/assets/101812544/b27a2bc0-8bb1-4bf1-9bef-1662c65d0e9c)

it doesn't Work for me i dunno if Ive downloaded it false but i used   $ pip3 install --upgrade GoogleBard

**Comment by acheong08** [comment]
This is a python installation issue. I am not responsible for getting your environment set up properly
