### ISSUE TITLE
Google Bard Encountered Error 

### ISSUE THREAD

**Issue by greengeckowizard** [acheong08/Bard#32]
Hi I've seen this issue on this project before but they seemed to be all closed 
Google Bard encountered an error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n54\n[["di",82],["af.httprm",83,"6657274337850409787",1]]\n25\n[["e",4,null,null,129]]\n'

Thank you very much this project is amazing.

**Comment by acheong08** [comment]
How did you fix it?

**Comment by jcmaciel** [comment]
i have this issue, how can I fix that?
