### ISSUE TITLE
Google Bard encountered an error:        

### ISSUE THREAD

**Issue by Ya-chunJen** [acheong08/Bard#4]
Google Bard encountered an error:                                                                                                  
b')]}'\n\n102\n[["er",null,null,null,null,400,null,null,null,3],["di",88],["af.httprm",88,"9026063738222580818",1]]\n25\n[["e",4,nu
ll,null,138]]\n'.

**Comment by acheong08** [comment]
Make sure your cookie and at token is correct

**Comment by Lin-Rexter** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/84280745/227540655-631b51ce-8cb9-4c4a-9c04-9d2bc2ff767a.png)
