### ISSUE TITLE
Showing error after every 2 or 3 chats

### ISSUE THREAD

**Issue by prateek-chaubey** [acheong08/Bard#41]
After every send 2 or 3 chats it's throwing an error

```
Google Bard encountered an error:
b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n55\n[["di",50],["a
f.httprm",50,"3088337182611657993",40]]\n25\n[["e",4,null,null,130]]\n
'.
```

And again starts working after restarting the bot and aborts after 2-3 messages

**Comment by acheong08** [comment]
Cannot replicate

**Comment by acheong08** [comment]
I got bored at 10

**Comment by Abhineetnehra** [comment]
> After every send 2 or 3 chats it's throwing an error
> 
> ```
> Google Bard encountered an error:
> b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n55\n[["di",50],["a
> f.httprm",50,"3088337182611657993",40]]\n25\n[["e",4,null,null,130]]\n
> '.
> ```
> 
> And again starts working after restarting the bot and aborts after 2-3 messages

I also encountered same issue.

**Comment by acheong08** [comment]
Can you guys check out https://github.com/dsdanielpark/Bard-API? @dsdanielpark seems to be keeping it much better maintained

**Comment by prateek-chaubey** [comment]
Both code seems to be similar, he just uses an extra language translator.
But the core concept of Bard is same

**Comment by acheong08** [comment]
Hmm. Perhaps see if you get any errors from the website.

Also:
![image](https://github.com/acheong08/Bard/assets/36258159/2d66af1c-53b8-4254-9732-c90d093acbee)

Could it be IP based?

**Comment by dsdanielpark** [comment]
[prateek-chaubey](https://github.com/prateek-chaubey)

In the PyPI version, it is almost the same, but since the cookie values are tied to the account, there is a possibility of being associated with **the account, and the possibility of IP cannot be ruled out.**

**Comment by PhoenixPhyre** [comment]
I updated this morning, and now I am getting this on instantiation, anyone else??

```
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python38\lib\site-packages\Bard.py", line 119, in Chatbot
    def load_conversations(self, file_path: str) -> list[dict]:
TypeError: 'type' object is not subscriptable
```
