### ISSUE TITLE
Add support for image responses

### ISSUE THREAD

**Issue by 676339784** [acheong08/Bard#42]
Bard now provides image responses. 

![Screenshot 2023-05-31 at 16 59 51](https://github.com/acheong08/Bard/assets/11021334/7908df9c-e878-412a-96b7-8b552e470e75)

Right now if you ask Bard for an image here is what the reply looks like 

```
You:
give me an image of what a desert looks like

Google Bard:
Sure, here is an image of a desert. [Image of Desert landscape]
```

Could the behavior be such that it shows a link to the image?

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/Bard/assets/36258159/ebb3735b-42e1-45e7-b7af-5820241eae86)

**Comment by acheong08** [comment]
Upgrade and that should be the default behavior
