### ISSUE TITLE
Add the new Image response feature in Bard

### ISSUE THREAD

**Issue by VanshShah1** [acheong08/Bard#46]

**Comment by VanshShah1** [comment]
So the adobe firefly in bard update will launch after a while, but do you know anyway I could get such unofficial api for adobe firefly just like you made it for bard. I found one on GitHub but it has a token field that's not clear where to get from.

**Comment by acheong08** [comment]
I haven't looked into Firefly since we already have Stable Diffusion which is imo much better. Afaik the token should come from the app. As for the integration with Bard, it is not public yet at least on my end

**Comment by Mrithul-E** [comment]
why output  don't contain any links

{'content': 'Sure thing! Here is an image of a cat.\n[Image of Cat]', 'conversation_id': 'c_62afcdf3c721b336', 'response_id': 'r_62afcdf3c721b129', 'factualityQueries': [], 'textQuery': ['image of cat', 1], 'choices': [{'id': 'rc_62afcdf3c721b20a', 'content': ['Sure thing! Here is an image of a cat.\n[Image of Cat]']}, {'id': 'rc_62afcdf3c721b1bf', 'content': ['Sure, here is an image of a cat.\n[Image of Cat]']}, {'id': 'rc_62afcdf3c721b174', 'content': ['Sure! Here is an image of a cat.\n[Image of Cat]']}]}

using python code provided in readme.md
