### ISSUE TITLE
Google Bard encountered an error

### ISSUE THREAD

**Issue by Lin-Rexter** [acheong08/Bard#5]
![image](https://user-images.githubusercontent.com/84280745/227540655-631b51ce-8cb9-4c4a-9c04-9d2bc2ff767a.png)

**Comment by acheong08** [comment]
Ensure your session token is correct. There is a `.` at the end of it that sometimes doesn't get copied.

**Comment by acheong08** [comment]
Please offer more debug if that is not the case

**Comment by Lin-Rexter** [comment]
I am not in the country of support.

> Please offer more debug if that is not the case

**Comment by acheong08** [comment]
Then you must use VPN/Proxy

**Comment by Lin-Rexter** [comment]
OK, thank you.

> Then you must use VPN/Proxy

**Comment by KrishnaRavi-99** [comment]
Retry this on an incognito tab and it should work. Also if you inputted the cookie id incorrectly the chat window shouldn't open up in the first place.

**Comment by adamfils2** [comment]
I get this error @acheong08 

{'content': 'Google Bard encountered an error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n57\\n[["di",228],["af.httprm",228,"5325340091289588626",16]]\\n25\\n[["e",4,null,null,132]]\\n\'.'}

**Comment by data-if** [comment]
got the same error:

```Google Bard encountered an error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",265],["af.httprm",265,"-6674487714863063807",0]]\n25\n[["e",4,null,null,132]]\n'.```

**Comment by tekemperor** [comment]
I got a similar error when I used `backtics` to reference a function in a code example from a previous response. This only happened once. The function was "unwrap" in Rust.

**Comment by Sellitus** [comment]
I'm getting this same error, though it was working before I did a full-upgrade for Ubuntu

**Comment by dheers73** [comment]
> ![image](https://user-images.githubusercontent.com/84280745/227540655-631b51ce-8cb9-4c4a-9c04-9d2bc2ff767a.png)

Hi ,
     I encountered the same issue. I was copying the right key but the issue was that I never logged on to bard.google.com and accepted its terms and conditions.Once I did that the Google account cookie got refreshed. I used the new cookie. Bingo! it worked.

**Comment by Lin-Rexter** [comment]
I forgot to close this issue, thanks everyone!

**Comment by ChandreshwarVish** [comment]
clear all the cookies and copy the new session_id and it worked!
