### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by Bharat9114** [acheong08/Bard#50]
![16863508214586319983982132447080](https://github.com/acheong08/Bard/assets/121393949/85a6b78c-5ff2-487c-b0a1-2deabeecc287)

Please go through this 
This error raised when i run Example.py

**Comment by acheong08** [comment]
Did you give the correct authentication cookie?

**Comment by Bharat9114** [comment]
Same i copied from cookie edit

**Comment by acheong08** [comment]
Are you signed in to multiple accounts?

**Comment by Bharat9114** [comment]
No only one . Infact i tried EDGE gpt also it's also showing Error. I want
to make ai bot for telegram.
I request you if you can basic version of bot that work with Telebot module
for python.

**Comment by acheong08** [comment]
The error check did not involve sending a request. It simply checked if the cookie ended with a `.` which all authentication cookies should. You copied it wrong

**Comment by acheong08** [comment]
And EdgeGPT uses a different cookie
