### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jabontz09** [acheong08/Bard#57]
getting this error when I try to run the Chatbot.ask() command
![image](https://github.com/acheong08/Bard/assets/27756050/ec08c603-a891-4f4b-9448-8b750f5035fa)

**Comment by Hikoboshi00** [comment]
Same here, hoping it gets fixed.

**Comment by lesleychou** [comment]
same here

**Comment by talhakabakus** [comment]
Same here as well.
