### ISSUE TITLE
Add proxy option

### ISSUE THREAD

**Issue by tylearymf** [acheong08/Bard#6]
Could you add a "proxy" property in the Chatbot constructor like in ChatGPT and EdgeGPT?

**Comment by acheong08** [comment]
`export all_proxy="socks5://host:port"`

**Comment by tylearymf** [comment]
I'm using the Process class in C# to start a Python process, like this:
```csharp
System.Diagnostics.Process.Start("python.exe", "main.py");
```

**Comment by tylearymf** [comment]
I tried setting the environment variable before starting the Python process, and it worked for proxying.
