### ISSUE TITLE
SNlm0e related error

### ISSUE THREAD

**Issue by vasanthsarathy** [acheong08/Bard#8]
Getting an error that the `resp.text` does not contain `SNlm0e` 
```
SNlM0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Thoughts?

**Comment by data-if** [comment]
I have the same problem, can you fix it?

**Comment by KrishnaRavi-99** [comment]
I got this error when I accidentally inputted the wrong cookie id.

**Comment by venuv** [comment]
the trailing '.' is part of the cookie id if that helps. with that added the Nonetype error went away

**Comment by HANiFLY** [comment]
GOT the same Nonetype problem even the value of "BARD_TOKEN" is with the trailing '.'

**Comment by breadbrowser** [comment]
> GOT the same Nonetype problem even the value of "BARD_TOKEN" is with the trailing '.'

same

**Comment by Alfex4936** [comment]
Maybe this try version: https://github.com/Alfex4936/Bard-rs

**Comment by acheong08** [comment]
This could happen if you guys are logged in on multiple accounts. Log in from a guest profile and try again

**Comment by acheong08** [comment]
> Maybe try this version: [Alfex4936/Bard-rs](https://github.com/Alfex4936/Bard-rs)

This worked for me as well
